### ISSUE TITLE
[BUG] node_exporter only configuration fails

### ISSUE THREAD

**Issue by lae** [saltstack-formulas/prometheus-formula#27]
### Formula commit hash / release tag
https://github.com/saltstack-formulas/prometheus-formula/tree/v3.3.0

### Versions reports (master & minion)
```
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 3.6.9 (default, Nov  7 2019, 10:44:02)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-72-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

### Pillar / config used
```
---
prometheus:
  wanted:
    - node_exporter
  use_upstream_archive: true
```

---

### Describe the bug

Salt state fails to apply when installing only node_exporter.

### Steps to reproduce the bug

Run state.apply with the above minimal pillar config, and Salt will error out with the following (which cascades into errors in dependent tasks):

```
          ID: prometheus-config-file-basedir-file-directory
    Function: file.directory
        Name: /opt/prometheus
      Result: False
     Comment: User prometheus is not available Group prometheus is not available
     Started: 11:01:21.656458
    Duration: 6.229 ms
     Changes:
```

### Expected behaviour

node_exporter successfully gets installed and configured.

### Attempts to fix the bug

I just changed the user attributes for the two states to a user that does get created in `config.users`. This works:

```diff
diff --git a/formulae/prometheus/archive/install.sls b/formulae/prometheus/archive/install.sls
index a60090f..4442236 100644
--- a/formulae/prometheus/archive/install.sls
+++ b/formulae/prometheus/archive/install.sls
@@ -14,8 +14,8 @@ include:
 prometheus-config-file-basedir-file-directory:
   file.directory:
     - name: {{ p.dir.basedir }}
-    - user: prometheus
-    - group: prometheus
+    - user: {{ p.wanted[0] }}
+    - group: {{ p.wanted[0] }}
     - mode: 755
     - makedirs: True
     - require:
diff --git a/formulae/prometheus/config/args/install.sls b/formulae/prometheus/config/args/install.sls
index 34fa74e..ab82b04 100644
--- a/formulae/prometheus/config/args/install.sls
+++ b/formulae/prometheus/config/args/install.sls
@@ -17,8 +17,8 @@ include:
 prometheus-config-file-args-file-directory:
   file.directory:
     - name: {{ prometheus.dir.args }}
-    - user: prometheus
-    - group: prometheus
+    - user: {{ prometheus.wanted[0] }}
+    - group: {{ prometheus.wanted[0] }}
     - mode: 755
     - makedirs: True
     - require:
```

### Additional context

I'm only starting to learn Salt/use this formula, so I haven't gone through the entire formula, but I'm not sure if this is the preferred method of resolving this issue (I don't think it is). Should the `prometheus` user get created? Or maybe these directories should default to the `root` user? Although looking at the affected directories, `/etc/default` actually shouldn't be owned by `prometheus` in the first place...

**Comment by myii** [comment]
@lae Thanks for the report.  I can confirm this bug using the given pillar:

* https://travis-ci.org/myii/prometheus-formula/builds/630081063

I don't use this formula myself but shouldn't Prometheus be installed as a prerequisite of the `node_exporter`?  If so, the `prometheus` user and group will be present and the state works fine:

* https://travis-ci.com/saltstack-formulas/prometheus-formula/jobs/269656135#L2667-L2685

As for `/etc/defaults` being managed directly, that's definitely a bug.  Probably a change required to this line:

https://github.com/saltstack-formulas/prometheus-formula/blob/7eede35f7b15ff5f4dfd6ef3a7b215cde2ddb97c/prometheus/defaults.yaml#L22

@noelmcloughlin This appears to have been implemented in #5.  Do you have any suggestions of how this should be resolved?

**Comment by lae** [comment]
Prometheus should not be installed as a prerequisite for `node_exporter`. The exporter is just a simple standalone binary that is meant to be deployed on hosts that are to be monitored, as it provides system-level metrics, and `prometheus` (also a standalone binary) is meant to be deployed on a host that would be doing the monitoring/scraping.

i.e. the following is an environment that is perfectly viable (and in fact what I did with Ansible at my previous job):

_monitor-host_: `prometheus`, `node_exporter`
_alertmanager-host_: `alertmanager`, `node_exporter`
_app-host_: `node_exporter`, `app_exporter`
_app-db-host_: `node_exporter`, `mysqld_exporter`

Where _monitor-host_ scrapes all of the exporters from each one of these hosts, and sends alerts to _alertmanager-host_.

**Comment by lae** [comment]
Also, regarding the `/etc/defaults` issue - this is a distro-specific (Debian variants) thing as far as I know. It probably shouldn't be managed on RedHat (which uses `/etc/sysconfig`), for example (while I haven't tested it, it doesn't look like it gets overridden in `osfamilymap.yaml`).

Also, the package install method (for `node_exporter` at least, but I haven't checked) may use `/etc/defaults`, but from what I could tell, the archive install method does not. The systemd unit file that gets installed doesn't seem to reference it at all.

**Comment by myii** [comment]
@lae Thanks for the additional info, I believe that will be helpful.  I'm going to have to defer this to the formula's authors, viz. @alxwr and @noelmcloughlin.  Hopefully, they'll be able to provide a resolution to the multiple issues raised here.

**Comment by noelmcloughlin** [comment]
#30
